import { useMemo, useState } from 'react'
import { ArrowDown, ArrowUpRight, BarChart3, Download, RotateCcw } from 'lucide-react'
import rawJson from './data/transportation.json'
import cleanedJson from './data/transportation-cleaned.json'
import analysisJson from './data/analysis-summary.json'
import type { AnalysisSummary, TransportationRecord } from './types/transportation'
import { currency, median, modeLabel, number, pValue, percent } from './utils/analytics'
import { CramersHeatmap, CostBoxplot, CostHistogram, Distribution, KendallChart, RelationshipScatter, relationships, type RelationshipKey } from './components/dashboard/Charts'
import { DataQuality, KeyInsights, StatisticalResults } from './components/dashboard/Findings'

const raw = rawJson as TransportationRecord[], cleaned = cleanedJson as TransportationRecord[], summary = analysisJson as AnalysisSummary
const sourceUrl = import.meta.env.VITE_SOURCE_URL || (window.location.hostname.endsWith('.github.io')
  ? `https://github.com/${window.location.hostname.split('.')[0]}/${window.location.pathname.split('/')[1] || window.location.hostname.split('.')[0] + '.github.io'}`
  : '#method')
type FilterKey = 'gender' | 'transportasi' | 'jenisKendaraan' | 'performaKendaraan'
const filterLabels: { key: FilterKey; label: string }[] = [{ key: 'gender', label: 'Gender' }, { key: 'transportasi', label: 'Transportation mode' }, { key: 'jenisKendaraan', label: 'Vehicle type' }, { key: 'performaKendaraan', label: 'Vehicle performance' }]
const emptyFilters: Record<FilterKey, string> = { gender: '', transportasi: '', jenisKendaraan: '', performaKendaraan: '' }

function Section({ number: index, eyebrow, title, children, id }: { number: string; eyebrow: string; title: string; children: React.ReactNode; id: string }) {
  return <section className="section" id={id}><div className="section-title"><div><span className="eyebrow">{index} / {eyebrow}</span><h2>{title}</h2></div><div className="section-rule" /></div>{children}</section>
}
function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="kpi"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
export default function App() {
  const [filters, setFilters] = useState(emptyFilters)
  const [dataset, setDataset] = useState<'raw' | 'cleaned'>('raw')
  const [relationship, setRelationship] = useState<RelationshipKey>('jarak')
  const [outlierVariable, setOutlierVariable] = useState<'umur' | 'jarak' | 'waktu' | 'biaya' | 'tingkatMobilitas'>('jarak')
  const [before, setBefore] = useState(true)
  const selectedData = dataset === 'raw' ? raw : cleaned
  const records = useMemo(() => selectedData.filter(r => filterLabels.every(({ key }) => !filters[key] || r[key] === filters[key])), [selectedData, filters])
  const reset = () => { setFilters(emptyFilters); setDataset('raw'); setRelationship('jarak') }
  const privateShare = records.length ? records.filter(r => r.transportasi === 'Kendaraan pribadi').length / records.length : 0
  const modeTest = summary.kruskal.find(t => t.variable === 'transportasi')!
  const ride = summary.groupCost['Ojek online']
  return <>
    <header className="site-header"><div className="shell header-inner"><div className="brand-mark"><BarChart3 size={20} strokeWidth={2.2} /></div><div className="brand"><h1>Student Transportation &amp; Mobility Analytics</h1><p>Transportation choices, travel behavior, and spending among TSD 2022 students</p></div><div className="header-actions"><span className="tech-label">R · Shiny · Statistical Analysis</span><a className="text-action" href={sourceUrl} target={sourceUrl.startsWith('http') ? '_blank' : undefined} rel="noreferrer">{sourceUrl.startsWith('http') ? 'View Source' : 'Project Details'} <ArrowUpRight size={14} /></a><a className="text-action" href={`${import.meta.env.BASE_URL}shiny/`}>R Shiny Demo <ArrowUpRight size={14} /></a><button className="text-action" onClick={reset}><RotateCcw size={14} /> Reset filters</button></div></div></header>
    <main className="shell">
      <div className="intro"><div><span className="eyebrow">FIELD STUDY / TSD 2022</span><p>An evidence-led view of how students move, what they spend, and what this small survey can—and cannot—tell us.</p></div><a href={`${import.meta.env.BASE_URL}data-baru.csv`} download className="download"><Download size={15} /> Download anonymous dataset</a></div>
      <div className="filter-wrap"><div className="filter-heading"><strong>Explore the sample</strong><span>Descriptive charts update with filters · statistical tests remain on the full cleaned dataset</span></div><div className="filter-grid">{filterLabels.map(({ key, label }) => <label key={key}>{label}<select value={filters[key]} onChange={e => setFilters(prev => ({ ...prev, [key]: e.target.value }))}><option value="">All {label.toLowerCase()}</option>{[...new Set(raw.map(r => r[key]))].sort().map(v => <option key={v} value={v}>{key === 'transportasi' ? modeLabel(v) : v}</option>)}</select></label>)}<label>Dataset<select value={dataset} onChange={e => setDataset(e.target.value as 'raw' | 'cleaned')}><option value="raw">Raw data</option><option value="cleaned">Cleaned data</option></select></label><button onClick={reset} className="reset-button"><RotateCcw size={14} /> Reset</button></div></div>
      {records.length === 0 ? <div className="empty-state">No observations match the selected filters. <button onClick={reset}>Reset filters</button></div> : <>
        <Section number="01" eyebrow="OVERVIEW" title="The sample at a glance" id="overview"><div className="kpi-grid"><Kpi label="Respondents" value={String(records.length)} detail={`${dataset === 'raw' ? summary.sample.raw : summary.sample.cleaned} in full ${dataset} dataset`} /><Kpi label="Median transport cost" value={currency(median(records.map(r => r.biaya)))} detail="reported spending" /><Kpi label="Median travel distance" value={`${number(median(records.map(r => r.jarak)))} km`} detail="home to campus" /><Kpi label="Median travel time" value={`${number(median(records.map(r => r.waktu)))} min`} detail="reported commute" /><Kpi label="Private vehicle share" value={percent(privateShare)} detail="of current view" /></div><div className="finding-banner"><span>KEY FINDING</span><p>Transportation spending differs across modes in the full cleaned sample <strong>({pValue(modeTest.pValue)})</strong>. Ride-hailing respondents have the highest observed group median at <strong>{currency(ride.median)}</strong>.</p><small>Omnibus Kruskal–Wallis test · n = {summary.sample.cleaned} · α = 0.05</small></div></Section>
        <Section number="02" eyebrow="CHOICES" title="How do students travel?" id="choices"><div className="grid-two"><Distribution records={records} field="transportasi" title="Transportation mode distribution" note="Respondents and share · current filter" /><Distribution records={records} field="jenisKendaraan" title="Vehicle type distribution" note="Respondents and share · current filter" /></div></Section>
        <Section number="03" eyebrow="SPENDING" title="How much do students spend?" id="spending"><div className="grid-two"><CostHistogram records={records} /><CostBoxplot records={records} dataset={dataset === 'raw' ? 'Raw data' : 'Cleaned data'} /></div></Section>
        <Section number="04" eyebrow="RELATIONSHIPS" title="What moves with cost?" id="relationships"><div className="grid-two"><RelationshipScatter records={records} selected={relationship} setSelected={setRelationship} summary={summary} /><KendallChart summary={summary} /></div><p className="section-footnote">Select {relationships.map(r => r.label.toLowerCase()).join(', ')} above. These observational associations do not establish causation.</p></Section>
      </>}
      <Section number="05" eyebrow="INFERENCE" title="Statistical findings" id="statistics"><div className="method-callout">Inferential statistics are fixed to the <strong>full cleaned dataset, n = {summary.sample.cleaned}</strong> (α = 0.05), independent of the filters above.</div><StatisticalResults summary={summary} /><div className="grid-two secondary-charts"><CramersHeatmap summary={summary} /><div className="panel advanced"><div className="panel-heading"><div><h3>Advanced analysis · PCA</h3><p>Standardized numeric variables · full cleaned dataset</p></div></div><div className="pca-rows">{summary.pca.explainedVariance.map((v, i) => <div key={i}><span>PC{i + 1}</span><div className="pca-track"><div style={{ width: percent(v) }} /></div><strong>{percent(v)}</strong></div>)}</div><p className="chart-insight">PC1 + PC2 explain {percent(summary.pca.explainedVariance[0] + summary.pca.explainedVariance[1])} of standardized numeric variance. PCA is exploratory here, not a causal model.</p></div></div></Section>
      <Section number="06" eyebrow="INTERPRETATION" title="Key insights" id="insights"><KeyInsights summary={summary} /></Section>
      <Section number="07" eyebrow="QUALITY" title="Data quality & preprocessing" id="quality"><DataQuality summary={summary} activeRecords={records} rawRecords={raw} cleanedRecords={cleaned} chart={outlierVariable} setChart={setOutlierVariable} before={before} setBefore={setBefore} /></Section>
      <Section number="08" eyebrow="METHOD" title="Methodology & limitations" id="method"><div className="pipeline">{['Survey data', 'Label cleaning', 'Exploration', 'IQR outliers', 'Normality', 'Non-parametric tests', 'Visualization', 'Insights'].map((step, i) => <div key={step}><span>{String(i + 1).padStart(2, '0')}</span><strong>{step}</strong>{i < 7 && <ArrowDown size={14} aria-hidden="true" />}</div>)}</div><div className="method-grid"><p>Outliers were identified using the 1.5 × IQR criterion. Descriptive overview metrics use raw data unless otherwise selected, while inferential statistical tests use the cleaned dataset. The original analysis applied bounds sequentially across numeric variables; this pipeline preserves that behavior.</p><p>This analysis is based on a small sample of TSD 2022 students and should not be generalized to the wider student population without additional sampling. Public transport has just {summary.groupCost['Kendaraan umum'].n} respondents; cost units for several tiny values also require source verification.</p></div></Section>
      <footer className="project-footer"><div><span className="eyebrow">ABOUT THIS PROJECT</span><h2>From coursework to an accessible analytical story.</h2><p>This project began as an Exploratory Data Visualization assignment built with R and Shiny. It was redesigned as an interactive analytics portfolio to improve data storytelling, statistical communication, reproducibility, and web accessibility.</p><p className="original-title">Original study: <em>Analisis Penggunaan Alat Transportasi Terhadap Pengeluaran Mahasiswa TSD 2022</em></p></div><div className="stack"><span>METHODS &amp; TOOLS</span><p>R / Shiny / Shinylive / React / TypeScript / Vite / Tailwind CSS / Apache ECharts / GitHub Pages</p><a href="#overview">Back to overview ↑</a></div></footer>
    </main>
  </>
}
